project_name: helm-diff
builds:
  - id: default
    main: .
    binary: bin/diff
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -X github.com/databus23/helm-diff/v3/cmd.Version={{ .Version }}
    goos:
      - freebsd
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    builds:
    - default
    format: tgz
    name_template: '{{ .ProjectName }}-{{ if eq .Os "darwin" }}macos{{ else }}{{ .Os }}{{ end }}-{{ .Arch }}'
    files:
    - README.md
    - plugin.yaml
    - LICENSE
changelog:
  use: github-native

release:
  prerelease: auto
