name: diff
# Version is the version of Helm plus the number of official builds for this
# plugin
version: "3.12.5"
usage: "Preview helm upgrade changes as a diff"
description: "Preview helm upgrade changes as a diff"
useTunnel: true
platformCommand:
  - os: linux 
    command: "${HELM_PLUGIN_DIR}/install-binary.sh"
  - os: darwin
    command: "${HELM_PLUGIN_DIR}/install-binary.sh"
  - os: windows
    command: pwsh
    args:
      - -c
      - ${HELM_PLUGIN_DIR}/install-binary.ps1

# v3.18.0+ only
# platformHooks:
#   install:
#     - command: ${HELM_PLUGIN_DIR}/install-binary.sh
#     - os: windows
#       command: pwsh
#       args:
#           - -c
#           - ${HELM_PLUGIN_DIR}/install-binary.ps1
#   update:
#     - command: ${HELM_PLUGIN_DIR}/install-binary.sh
#       args:
#         - -u
#     - os: windows
#       command: pwsh
#       args:
#         - -c
#         - ${HELM_PLUGIN_DIR}/install-binary.ps1
#         - -Update