name: "diff"
# Version is the version of Helm plus the number of official builds for this
# plugin
version: "3.0.0-rc.1"
usage: "Preview helm upgrade changes as a diff"
description: "Preview helm upgrade changes as a diff"
useTunnel: true
command: "$HELM_PLUGIN_DIR/bin/diff"
hooks:
  install: "cd $HELM_PLUGIN_DIR; ./install-binary.sh"
  update: "cd $HELM_PLUGIN_DIR; ./install-binary.sh"